"""Generator that produces a query's rubric: the criteria a complete answer must satisfy.

prose-check: off -- the bulk of this module is LLM prompt templates, which are data.
"""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING, Any

from ragelo.llm_providers.base_llm_provider import BaseLLMProvider, get_llm_provider
from ragelo.types.answer_formats import Criterion, RubricSchema
from ragelo.types.configurations import RubricGeneratorConfig
from ragelo.types.evaluables import ChatMessage
from ragelo.types.formats import LLMInputPrompt
from ragelo.types.query import Query
from ragelo.utils import call_async_fn, get_pbar, string_to_template

if TYPE_CHECKING:
    from ragelo.types.experiment import Experiment

logger = logging.getLogger(__name__)


class RubricGenerator:
    """Writes `query.rubric`, the artifact every rubric evaluator grades against."""

    documents_system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a set of relevant retrieved documents, create a rubric for evaluating the quality of reports generated by other agents.
        You should think deeply and carefully about what questions should a complete and high-quality report that answer the question should answer.
        Each criterion should be a short yes/no question that can be used to evaluate the quality of the responses.
        You should write {{ n_criteria }} criteria.
        If a criterion is supported by a document, you should include the document ID in the evidence list for that criterion.
        You may optionally assign a weight (a positive number) to each criterion to indicate its relative importance. More important criteria should have higher weights. If no weight is provided, all criteria are weighted equally.
        """
    )

    documents_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        {% if conversation_context %}
        [Conversation Context]
        {% for msg in conversation_context %}
        {{ msg }}
        {% endfor %}
        {% endif %}

        [Retrieved Documents]
        {% for doc in documents %}
        [[{{doc.did}}]] {{doc.text}}
        --------------------------------
        {% endfor %}
        """)

    reference_answer_system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a known-correct answer to it, decompose that answer into a rubric for evaluating answers written by other agents.
        Each criterion should be a short yes/no question about one piece of information a complete answer must contain.
        You should write at most {{ n_criteria }} criteria, and fewer if the correct answer does not support that many.
        Every criterion must be supported by the correct answer: do not add criteria for information it does not contain, and do not restate the same information as two criteria.
        If the correct answer attributes a piece of information to a source, include that source in the evidence list for the criterion.
        You may optionally assign a weight (a positive number) to each criterion to indicate its relative importance. More important criteria should have higher weights. If no weight is provided, all criteria are weighted equally.
        """
    )

    reference_answer_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        [Correct Answer]
        {{ query.reference_answer }}
        """)

    def __init__(self, config: RubricGeneratorConfig, llm_provider: BaseLLMProvider):
        self.config = config
        self.llm_provider = llm_provider

    def generate(self, query: Query, conversation_context: list[ChatMessage] | None = None) -> list[Criterion]:
        return call_async_fn(self.generate_async, query, conversation_context)

    async def generate_async(
        self, query: Query, conversation_context: list[ChatMessage] | None = None
    ) -> list[Criterion]:
        """Generates the criteria for a single query. Does not write them to the query."""
        llm_input = self._build_message(query, conversation_context)
        llm_response = await self.llm_provider.call_async(llm_input, response_schema=RubricSchema)
        rubric = llm_response.parsed_answer
        if not isinstance(rubric, RubricSchema):
            raise TypeError(f"Expected a RubricSchema for query {query.qid}, got {type(rubric)}")
        return rubric.criteria

    def generate_experiment(
        self,
        experiment: Experiment,
        n_threads: int | None = None,
        force: bool = False,
        should_save: bool = True,
        conversation_contexts: dict[str, list[ChatMessage]] | None = None,
    ) -> None:
        """Writes `query.rubric` for every query in the experiment that does not have one."""
        n_threads = n_threads or self.config.n_processes
        call_async_fn(
            self._generate_experiment_async,
            experiment,
            n_threads,
            force or self.config.force,
            conversation_contexts or {},
        )
        if should_save:
            experiment.save()

    async def _generate_experiment_async(
        self,
        experiment: Experiment,
        n_threads: int,
        force: bool,
        conversation_contexts: dict[str, list[ChatMessage]],
    ) -> None:
        queries = [q for q in experiment if force or not q.rubric]
        if not queries:
            logger.info(f"All {len(list(experiment))} queries already have a rubric.")
            return
        pbar = get_pbar(
            len(queries),
            self.config.rich_print,
            desc="Generating rubrics",
            disable=not self.config.use_progress_bar,
        )
        semaphore = asyncio.Semaphore(n_threads)

        async def generate_one(query: Query) -> None:
            async with semaphore:
                try:
                    query.rubric = await self.generate_async(query, conversation_contexts.get(query.qid))
                except Exception as e:  # noqa: BLE001
                    logger.warning(f"Failed to generate a rubric for query {query.qid}: {e}")
                pbar.update()

        await asyncio.gather(*(generate_one(q) for q in queries))
        pbar.close()

    def _build_message(self, query: Query, conversation_context: list[ChatMessage] | None) -> LLMInputPrompt:
        context: dict[str, Any] = {
            "expert_in": self.config.expert_in,
            "company": self.config.company,
            "n_criteria": self.config.n_criteria,
            "query": query,
        }
        if self.config.source == "reference_answer":
            if not query.reference_answer:
                raise ValueError(
                    f"Query {query.qid} has no reference_answer, which the "
                    f"{self.config.source} rubric source decomposes into criteria."
                )
            system_prompt = self.reference_answer_system_prompt
            user_prompt = self.reference_answer_user_prompt
        else:
            if not query.retrieved_docs:
                raise ValueError(
                    f"Query {query.qid} has no retrieved documents, which the "
                    f"{self.config.source} rubric source derives criteria from."
                )
            system_prompt = self.documents_system_prompt
            user_prompt = self.documents_user_prompt
            context["documents"] = list(query.retrieved_docs.values())
            context["conversation_context"] = conversation_context or []
        return LLMInputPrompt(
            system_prompt=system_prompt.render(**context),
            user_message=user_prompt.render(**context),
        )


def get_rubric_generator(
    llm_provider: BaseLLMProvider | str = "openai",
    config: RubricGeneratorConfig | None = None,
    **kwargs,
) -> RubricGenerator:
    if isinstance(llm_provider, str):
        llm_provider = get_llm_provider(llm_provider, **kwargs)
    if config is None:
        valid_keys = [field for field in RubricGeneratorConfig.model_fields]
        config = RubricGeneratorConfig(**{k: v for k, v in kwargs.items() if k in valid_keys})
    return RubricGenerator(config, llm_provider)
