from __future__ import annotations

import itertools
import logging
import random
from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Callable, Literal, TypeVar, get_type_hints

from pydantic import BaseModel

from ragelo.evaluators.base_evaluator import BaseEvaluator, T_Result
from ragelo.llm_providers.base_llm_provider import BaseLLMProvider, get_llm_provider
from ragelo.types import AnswerEvaluatorResult, LLMInputPrompt, PairwiseGameEvaluatorResult, Query
from ragelo.types.answer_formats import PairwiseEvaluationAnswer, RubricAnswerFormat
from ragelo.types.configurations import BaseAnswerEvaluatorConfig, PairwiseEvaluatorConfig
from ragelo.types.evaluables import AgentAnswer, Document, Evaluable, PairwiseGame
from ragelo.types.types import AnswerEvaluatorTypes, _result_type_registry
from ragelo.utils import call_async_fn, get_placeholders_and_tags

logger = logging.getLogger(__name__)

T_AnswerConfig = TypeVar("T_AnswerConfig", bound=BaseAnswerEvaluatorConfig)
PairwiseWinner = Literal["A", "B", "C"]

if TYPE_CHECKING:
    from ragelo.types.experiment import Experiment


class BaseAnswerEvaluator(BaseEvaluator[T_AnswerConfig, T_Result]):
    config: T_AnswerConfig
    evaluable_name: str = "Agent Answer"
    _warned_queries: set[str] = set()
    result_type: type[T_Result] = AnswerEvaluatorResult  # type: ignore[assignment]

    def evaluate(
        self,
        query: Query | str,
        answer: AgentAnswer | str | None = None,
        answer_a: AgentAnswer | str | None = None,
        answer_b: AgentAnswer | str | None = None,
        retrieved_documents: list[Document | str] | str | None = None,
        document_metadata: list[dict[str, Any]] | None = None,
        query_metadata: dict[str, Any] | None = None,
        answer_metadata: dict[str, Any] | None = None,
        answer_a_metadata: dict[str, Any] | None = None,
        answer_b_metadata: dict[str, Any] | None = None,
    ) -> AnswerEvaluatorResult:
        """
        Evaluates a single sample using an answer evaluator.
        Args:
            query(Query|str): The query to evaluate.
                If a string is provided, a Query object will be created with the provided query_metadata.
            answer(Optional[AgentAnswer|str]): The answer generated by an agent to evaluate.
                If a string is provided, the AgentAnswer object will be created with the provided answer_metadata
            answer_a(Optional[AgentAnswer|str]): The first answer generated by an agent to evaluate.
                Only used if the evaluator is pairwise.
            answer_b(Optional[AgentAnswer|str]): The second answer generated by an agent to evaluate.
                Only used if the evaluator is pairwise.
            retrieved_documents(Optional[list[str]|list[Document]]): The documents retrieved by the agent.
            document_metadata(Optional[list[dict[str, Any]]): The metadata of the documents retrieved by the agent.
            query_metadata(Optional[dict[str, Any]]): The metadata for the query.
            answer_metadata(Optional[dict[str, Any]]): The metadata for the answer.
            answer_a_metadata(Optional[dict[str, Any]]): The metadata for the first answer.
                Only used if the evaluator is pairwise.
            answer_b_metadata(Optional[dict[str, Any]]): The metadata for the second answer.
                Only used if the evaluator is pairwise.
        Returns:
            AnswerEvaluatorResult: The result of the evaluation.
        """
        query = Query.build(query, query_metadata)

        if isinstance(retrieved_documents, str):
            retrieved_documents = [retrieved_documents]

        if retrieved_documents:
            retrieved_and_assembled_docs = Document.assemble_documents(
                retrieved_documents, query.qid, document_metadata
            )
            query.retrieved_docs = retrieved_and_assembled_docs

        agent: str | tuple[str, str]
        evaluable: AgentAnswer | PairwiseGame

        if self.config.pairwise:
            if not answer_a or not answer_b:
                raise ValueError("Pairwise evaluations require two answers")
            answer_a = AgentAnswer.assemble_answer(answer_a, query.qid, metadata=answer_a_metadata)
            answer_b = AgentAnswer.assemble_answer(answer_b, query.qid, metadata=answer_b_metadata)
            agent = (answer_a.agent, answer_b.agent)
            evaluable = PairwiseGame(
                qid=query.qid,
                agent_a_answer=answer_a,
                agent_b_answer=answer_b,
            )
        else:
            if not answer:
                raise ValueError("Pointwise evaluations require an answer")
            evaluable = AgentAnswer.assemble_answer(answer, query.qid, metadata=answer_metadata)
            agent = evaluable.agent
        result = call_async_fn(self.evaluate_async, (query, evaluable))

        if result.exception or result.answer is None:
            raise ValueError(
                f"Failed to evaluate qid: {query.qid} agent(s): {agent}",
                f"Exception: {result.exception}",
            )
        return result

    def evaluate_experiment(self, experiment: Experiment, n_threads: int | None = None):
        """
        Trigger the evaluation of all the queries in the experiment.
        The evaluation is done in asynchronously with the number of threads defined in config.n_processes parameter.
        This can be overwritten by the n_threads parameter.

        Args:
            experiment(Experiment): The experiment to evaluate.
            n_threads(int): The number of threads to use for the evaluation.
                If None, the number of threads defined in the config will be used.
        """
        if self.config.pairwise:
            self.__add_pairwise_games(experiment)
        super().evaluate_experiment(experiment, n_threads)

    async def evaluate_async(
        self, eval_sample: tuple[Query, Evaluable]
    ) -> AnswerEvaluatorResult | PairwiseGameEvaluatorResult:
        """
        Evaluates a single sample (either an answer or a pairwise game) asynchronously.
        Args:
            eval_sample (tuple[Query, Evaluable]): The query and evaluable to evaluate.
        """

        query, evaluable = eval_sample
        if not isinstance(evaluable, (AgentAnswer, PairwiseGame)):
            raise ValueError(f"can't evaluate a {type(evaluable).__name__} in an Answer Evaluator")
        if isinstance(evaluable, PairwiseGame):
            return await self.__evaluate_game(query, evaluable)
        return await self.__evaluate_answer(query, evaluable)

    async def __evaluate_answer(self, query: Query, answer: AgentAnswer) -> AnswerEvaluatorResult:
        evaluator_name = str(self.config.evaluator_name)
        if evaluator_name in answer.evaluations and not self.config.force:
            cached = answer.evaluations[evaluator_name]
            if isinstance(cached, AnswerEvaluatorResult):
                return cached

        prompt = self._build_message(query, answer)
        response_schema = self._resolve_response_schema(prompt)

        exc = None
        parsed_answer = None
        raw_answer = ""
        try:
            llm_response = await self.llm_provider.call_async(input=prompt, response_schema=response_schema)  # type: ignore[arg-type]
            llm_response = self._process_answer(llm_response, query)
            parsed_answer = llm_response.parsed_answer
            raw_answer = llm_response.raw_answer
        except Exception as e:
            exc = str(e) + f"\nRaw answer: {raw_answer}"
            logger.warning(f"Failed to generate answer for qid: {query.qid} and agent: {answer.agent}: {exc}")

        return AnswerEvaluatorResult(
            qid=query.qid,
            agent=answer.agent,
            evaluator_name=evaluator_name,
            answer=parsed_answer,  # type: ignore[arg-type]
            exception=exc,
        )

    async def __evaluate_single_game(self, query: Query, game: PairwiseGame) -> PairwiseGameEvaluatorResult:
        evaluator_name = str(self.config.evaluator_name)

        prompt = self._build_message_pairwise(query, game)
        response_schema = self._resolve_response_schema(prompt)

        exc = None
        parsed_answer = None
        raw_answer = ""
        try:
            llm_response = await self.llm_provider.call_async(input=prompt, response_schema=response_schema)  # type: ignore[arg-type]
            llm_response = self._process_answer(llm_response, query)
            parsed_answer = llm_response.parsed_answer
            raw_answer = llm_response.raw_answer
        except Exception as e:
            exc = str(e) + f"\nRaw answer: {raw_answer}"
            logger.warning(
                f"Failed to evaluate game for qid: {query.qid} "
                f"agents: ({game.agent_a_answer.agent}, {game.agent_b_answer.agent}): {exc}"
            )

        return PairwiseGameEvaluatorResult(
            qid=query.qid,
            agent_a=game.agent_a_answer.agent,
            agent_b=game.agent_b_answer.agent,
            evaluator_name=evaluator_name,
            answer=parsed_answer,  # type: ignore[arg-type]
            exception=exc,
        )

    async def __evaluate_game(self, query: Query, game: PairwiseGame) -> PairwiseGameEvaluatorResult:
        evaluator_name = str(self.config.evaluator_name)
        if evaluator_name in game.evaluations and not self.config.force:
            cached = game.evaluations[evaluator_name]
            if isinstance(cached, PairwiseGameEvaluatorResult):
                return cached

        # Evaluate in both directions
        normal_game = PairwiseGame(
            qid=game.qid,
            agent_a_answer=game.agent_a_answer,
            agent_b_answer=game.agent_b_answer,
        )
        reversed_game = PairwiseGame(
            qid=game.qid,
            agent_a_answer=game.agent_a_answer,
            agent_b_answer=game.agent_b_answer,
        )

        a_vs_b_result = await self.__evaluate_single_game(query, normal_game)
        b_vs_a_result = await self.__evaluate_single_game(query, reversed_game)

        # Reconcile winners
        winner_normal = a_vs_b_result.winner
        winner_reversed = b_vs_a_result.winner

        # Normalize reversed winner back to original agent perspective
        if winner_reversed == "A":
            normalized_reversed: PairwiseWinner | None = "B"
        elif winner_reversed == "B":
            normalized_reversed = "A"
        else:
            normalized_reversed = winner_reversed  # None or "C"

        if winner_normal is not None and winner_normal == normalized_reversed:
            # Both directions agree on the same winner
            final_winner = winner_normal
            answer_source = a_vs_b_result.answer
        elif winner_normal in ("A", "B") and normalized_reversed in ("C", None):
            # One win + one tie → count the win
            final_winner = winner_normal
            answer_source = a_vs_b_result.answer
        elif normalized_reversed in ("A", "B") and winner_normal in ("C", None):
            # One tie + one win → count the win
            final_winner = normalized_reversed
            answer_source = self._canonicalize_pairwise_answer(b_vs_a_result.answer)
        else:
            # Full disagreement (A wins one way, B wins the other) → tie
            final_winner = "C"
            answer_source = a_vs_b_result.answer

        # Build parent result with reconciled winner
        parent_answer = None
        if answer_source is not None:
            parent_answer = answer_source.model_copy(update={"winner": final_winner})

        exc = a_vs_b_result.exception or b_vs_a_result.exception

        return PairwiseGameEvaluatorResult(
            qid=query.qid,
            agent_a=game.agent_a_answer.agent,
            agent_b=game.agent_b_answer.agent,
            evaluator_name=evaluator_name,
            answer=parent_answer,
            exception=exc,
            a_vs_b_result=a_vs_b_result,
            b_vs_a_result=b_vs_a_result,
        )

    def _canonicalize_pairwise_answer(
        self,
        answer: PairwiseEvaluationAnswer | RubricAnswerFormat | None,
    ) -> PairwiseEvaluationAnswer | RubricAnswerFormat | None:
        if answer is None:
            return None
        return answer.swap_perspective()

    def _resolve_response_schema(self, prompt: LLMInputPrompt) -> type[BaseModel] | None:
        schema = prompt.llm_response_schema or self.config.llm_response_schema
        if schema is not None:
            if isinstance(schema, type):
                return schema
            return None
        # Fall back to extracting from result_type
        answer_field = self.result_type.model_fields.get("answer")
        if not answer_field or not answer_field.annotation:
            return None
        answer_type = answer_field.annotation
        if hasattr(answer_type, "__args__"):
            answer_type = next(
                (arg for arg in answer_type.__args__ if arg is not type(None)),
                answer_type,
            )
        return answer_type

    def _get_all_evaluables(self, query: Query) -> list[Evaluable]:
        if self.config.pairwise:
            return list(query.pairwise_games.values())
        return list(query.answers.values())

    def _get_tuples_to_evaluate(self, experiment: Experiment) -> Sequence[tuple[Query, Evaluable]]:
        """
        Creates the list of pairs (query, evaluable) to evaluate
        """
        tuples_to_eval: list[tuple[Query, Evaluable]] = []
        all_tuples = 0
        missing_evaluations = 0
        evaluator_name = str(self.config.evaluator_name)
        for q in experiment:
            if self.config.pairwise:
                for g in q.pairwise_games.values():
                    all_tuples += 1
                    tuples_to_eval.append((q, g))
                    if evaluator_name not in g.evaluations:
                        missing_evaluations += 1

            else:
                for a in q.answers.values():
                    all_tuples += 1
                    tuples_to_eval.append((q, a))
                    if evaluator_name not in a.evaluations:
                        missing_evaluations += 1

        if missing_evaluations == 0 and not self.config.force:
            logger.info(
                f"All {all_tuples} answers are already evaluated.\n"
                "If you want to re-evaluate them, use the --force flag"
            )

        return tuples_to_eval

    def _build_message(self, query: Query, answer: AgentAnswer) -> LLMInputPrompt:
        """Builds the message to send to the LLM evaluator"""
        documents = self._filter_documents(query)
        context = {"query": query, "answer": answer, "documents": documents}
        user_message = self.user_prompt.render(**context)
        system_prompt = self.system_prompt.render(**context)
        return LLMInputPrompt(
            system_prompt=system_prompt,
            user_message=user_message,
        )

    def _build_message_pairwise(self, query: Query, game: PairwiseGame) -> LLMInputPrompt:
        """Builds the message to send to the LLM evaluator based on a pairwise game"""
        documents = self._filter_documents(query)
        context = {"query": query, "game": game, "documents": documents}
        user_message = self.user_prompt.render(**context)
        system_prompt = self.system_prompt.render(**context)
        return LLMInputPrompt(
            system_prompt=system_prompt,
            user_message=user_message,
        )

    @classmethod
    def from_config(cls, config: T_AnswerConfig, llm_provider: BaseLLMProvider):
        return cls(config, llm_provider)

    @classmethod
    def get_config_class(cls) -> type[BaseAnswerEvaluatorConfig]:
        return get_type_hints(cls)["config"]

    def __add_pairwise_games(self, experiment: Experiment):
        if not self.config.pairwise:
            return
        if not isinstance(self.config, PairwiseEvaluatorConfig):
            raise ValueError("Trying to add pairwise games to a non-pairwise evaluator")
        for query in experiment:
            query_agents = list(query.answers.keys())
            pairs = list(itertools.combinations(query_agents, 2))
            random.shuffle(pairs)

            # Filter out games that already exist
            existing_games = [g for g in pairs if query.get_pairwise_game(g[0], g[1]) is not None]
            games = [g for g in pairs if g not in existing_games]

            games_to_add = min(self.config.n_games_per_query - len(existing_games), len(games))
            games = games[:games_to_add]
            for agent_a, agent_b in games:
                query.add_pairwise_game(agent_a, agent_b)
        experiment.save()

    def _filter_documents(self, query: Query) -> list[Document]:
        # Check if we will actually include documents in any prompt
        system_placeholders: set[str] = set()
        user_placeholders: set[str] = set()
        system_placeholders = get_placeholders_and_tags(self.system_prompt)
        if self.user_prompt:
            user_placeholders = get_placeholders_and_tags(self.user_prompt)
        all_placeholders = system_placeholders | user_placeholders
        if "documents" not in all_placeholders:
            return []

        if not (
            self.config.include_raw_documents
            or self.config.include_relevance_score
            or self.config.include_relevance_reasoning
        ):
            return []

        documents = []
        for did, d in query.retrieved_docs.items():
            if self.config.document_relevance_threshold is not None:
                # Skip documents with relevance below the threshold
                if not d.evaluations:
                    continue
                # Get the first available retrieval evaluation
                score = None
                for _, evaluation in d.evaluations.items():
                    if hasattr(evaluation, "answer"):
                        answer = evaluation.answer
                        if isinstance(answer, dict):
                            score = answer.get("score")
                        elif isinstance(answer, BaseModel):
                            score = getattr(answer, "score", None)
                        else:
                            score = answer
                        if score is not None:
                            break

                if score is None:
                    continue
                if isinstance(score, str) and score.isdigit():
                    score = int(score)
                if not isinstance(score, (int, float)):
                    continue
                if score < self.config.document_relevance_threshold:
                    continue
            if self.config.document_filter is not None and not self.config.document_filter(d):
                continue
            documents.append(d)
        if len(documents) == 0:
            if query.qid not in self._warned_queries:
                logger.warning(
                    f"No relevant documents were retrieved for the query {query.qid}. "
                    "No documents will be provided to the Answer Evaluator."
                )
                self._warned_queries.add(query.qid)
        return documents


class AnswerEvaluatorFactory:
    registry: dict[AnswerEvaluatorTypes, type[BaseAnswerEvaluator]] = {}

    @classmethod
    def register(cls, name: AnswerEvaluatorTypes) -> Callable:
        def inner_wrapper(wrapped_class: type[BaseAnswerEvaluator]):
            if name in cls.registry:
                logger.warning(f"Overwriting {name} in registry")
            cls.registry[name] = wrapped_class
            _result_type_registry[f"answer:{name}"] = wrapped_class.result_type
            return wrapped_class

        return inner_wrapper

    @classmethod
    def get_evaluator_result_type(
        cls, evaluator_name: AnswerEvaluatorTypes
    ) -> type[AnswerEvaluatorResult] | type[PairwiseGameEvaluatorResult]:
        """Gets the answer evaluator result type for a specific evaluator type.

        Args:
            evaluator_name (AnswerEvaluatorTypes): The name of the evaluator.

        Returns:
            type: The answer evaluator result type for the evaluator.
        """
        if evaluator_name not in cls.registry:
            raise ValueError(
                f"Unknown answer evaluator {evaluator_name}\nValid options are {list(cls.registry.keys())}"
            )
        evaluator_class = cls.registry[evaluator_name]
        return evaluator_class.result_type  # type: ignore

    @classmethod
    def create(
        cls,
        evaluator_name: AnswerEvaluatorTypes,
        llm_provider: BaseLLMProvider | str,
        config: BaseAnswerEvaluatorConfig | None = None,
        **kwargs,
    ) -> BaseAnswerEvaluator:
        if evaluator_name not in cls.registry:
            raise ValueError(
                f"Unknown answer evaluator {evaluator_name}\nValid options are {list(cls.registry.keys())}"
            )
        if isinstance(llm_provider, str):
            llm_provider_instance = get_llm_provider(llm_provider, **kwargs)
        else:
            llm_provider_instance = llm_provider
        if config is None:
            class_ = cls.registry[evaluator_name]
            type_config = class_.get_config_class()
            valid_keys = [field for field in type_config.model_fields]
            valid_args = {k: v for k, v in kwargs.items() if k in valid_keys}
            required_fields = [arg for arg, info in type_config.model_fields.items() if info.is_required()]
            for field in required_fields:
                if field not in valid_args:
                    raise ValueError(f"Required argument {field} for evaluator {evaluator_name} not provided")
            config = type_config(**valid_args)
        return cls.registry[evaluator_name].from_config(config, llm_provider_instance)


def get_answer_evaluator(
    evaluator_name: AnswerEvaluatorTypes | str | None = None,
    llm_provider: BaseLLMProvider | str = "openai",
    config: BaseAnswerEvaluatorConfig | None = None,
    **kwargs,
) -> BaseAnswerEvaluator:
    """Gets an answer evaluator
    Args:
        evaluator_name (AnswerEvaluatorTypes | str | None): The name of the answer evaluator to get.
        llm_provider (BaseLLMProvider | str): The LLM provider to use for the evaluation.
        config (BaseAnswerEvaluatorConfig | None): The configuration for the answer evaluator.
        **kwargs: Additional arguments to pass to the answer evaluator.
    Returns:
        BaseAnswerEvaluator: The answer evaluator.
    """
    if evaluator_name is None:
        # get the name from the config
        if config is None:
            raise ValueError("Either the evaluator_name or a config object must be provided")
        evaluator_name = config.evaluator_name
    if isinstance(evaluator_name, str):
        try:
            evaluator_name = AnswerEvaluatorTypes(evaluator_name)
        except ValueError:
            raise ValueError(f"Unknown answer evaluator {evaluator_name}")
    if evaluator_name is None:
        raise ValueError("The evaluator_name must be provided")
    return AnswerEvaluatorFactory.create(
        evaluator_name,
        llm_provider=llm_provider,
        config=config,
        **kwargs,
    )


def get_answer_evaluator_result_type(
    evaluator_name: AnswerEvaluatorTypes | str,
) -> type[AnswerEvaluatorResult] | type[PairwiseGameEvaluatorResult]:
    """Gets the answer evaluator result type for a specific evaluator type.

    Args:
        evaluator_name (AnswerEvaluatorTypes | str): The name of the answer evaluator.

    Returns:
        type: The answer evaluator result type for the evaluator.
    """
    if isinstance(evaluator_name, str):
        try:
            evaluator_name = AnswerEvaluatorTypes(evaluator_name)
        except ValueError:
            raise ValueError(f"Unknown answer evaluator {evaluator_name}")
    return AnswerEvaluatorFactory.get_evaluator_result_type(evaluator_name)
