from __future__ import annotations

from typing import Type

from pydantic import BaseModel, Field, create_model

from ragelo.evaluators.answer_evaluators.base_answer_evaluator import AnswerEvaluatorFactory, BaseAnswerEvaluator
from ragelo.types.answer_formats import CriterionEvaluationPointwise, RubricPointwiseAnswerFormat, RubricSchema
from ragelo.types.configurations import RubricPointwiseEvaluatorConfig
from ragelo.types.evaluables import AgentAnswer, Document
from ragelo.types.formats import LLMInputPrompt, LLMResponseType
from ragelo.types.query import Query
from ragelo.types.results import AnswerEvaluatorResult
from ragelo.types.types import AnswerEvaluatorTypes
from ragelo.utils import call_async_fn, string_to_template


@AnswerEvaluatorFactory.register(AnswerEvaluatorTypes.RUBRIC_POINTWISE)
class RubricPointwiseEvaluator(BaseAnswerEvaluator[RubricPointwiseEvaluatorConfig, AnswerEvaluatorResult]):
    config: RubricPointwiseEvaluatorConfig
    result_type = AnswerEvaluatorResult

    criteria_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a set of relevant retrieved documents, create a rubric for evaluating the quality of reports generated by other agents.
        You should think deeply and carefully about what questions should a complete and high-quality report that answer the question should answer. 
        Each criterion should be a short yes/no question that can be used to evaluate the quality of the responses. 
        You should write {{ n_criteria }} criteria.
        If a criterion is supported by a document, you should include the document ID in the supporting_documents list for that criterion.
        You may optionally assign a weight (a positive number) to each criterion to indicate its relative importance. More important criteria should have higher weights. If no weight is provided, all criteria are weighted equally.
        """  # noqa: E501
    )

    criteria_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        [Retrieved Documents]
        {% for doc in documents %}
        [[{{doc.did}}]] {{doc.text}}
        --------------------------------
        {% endfor %}
        """)

    system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %} 
        You are tasked with evaluating the quality of a report written by a deep research agent in response of a user's question.
        The report was written based on a set of documents retrieved by the agent, and should thoroughly answer the user's question based exclusively on the relevant documents retrieved by the agent.

        To properly evaluate the quality of the report, you will be provided with a list of criteria to evaluate its quality.
        Each criterion includes a short question, an optional weight indicating its relative importance, and a list of documents that support the inclusion of the criterion in the report.
        For each criterion, you should think carefully about wether the report answers the criterion, and include a brief reasoning for your decision.

        You should think carefully about the criteria and the answers, and assign the final judgement accordingly.

        ## Criteria
        {% for criteria in criteria.criteria %}
        Criterion: {{criteria.criterion_name}}
        {% if criteria.weight is not none %}Weight: {{criteria.weight}}
        {% endif %}Supporting Documents: {{criteria.supporting_documents}}
        Short Question: {{criteria.short_question}}
        --------------------------------
        {% endfor %}
        """  # noqa: E501
    )

    user_prompt = string_to_template("""
        [User Question]
            {{query.query}}

        [Agent's Report]
            {{ answer.text }}
        """)

    criteria_cache: dict[str, RubricSchema]
    answer_schema_cache: dict[str, Type[BaseModel]]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.config.rubrics:
            self.criteria_cache = {qid: RubricSchema(criteria=rubrics) for qid, rubrics in self.config.rubrics.items()}
        else:
            self.criteria_cache = {}
        self.answer_schema_cache = {}

    def _build_evaluation_schema(self, criteria: RubricSchema) -> Type[BaseModel]:
        criteria_models = {}
        for criterion in criteria.criteria:
            criteria_models[criterion.criterion_name] = create_model(
                criterion.criterion_name,
                reasoning=(
                    str,
                    Field(
                        description="A brief explanation about your judgement, "
                        "and why you believe the report fulfills or not the criterion"
                    ),
                ),
                fulfillment=(
                    bool,
                    Field(description="Whether the report fulfills the criterion or not"),
                ),
            )
        return create_model("EvaluationSchema", **criteria_models)  # type: ignore[call-overload]

    async def _build_criteria(self, query: Query, documents: list[Document]) -> RubricSchema:
        if query.qid in self.criteria_cache:
            criteria = self.criteria_cache[query.qid]
        else:
            documents = self._filter_documents(query)
            context = {
                "expert_in": self.config.expert_in,
                "company": self.config.company,
                "documents": documents,
                "query": query,
                "n_criteria": self.config.n_criteria,
            }
            criteria_prompt = self.criteria_prompt.render(context)
            user_prompt = self.criteria_user_prompt.render(context)
            llm_input = LLMInputPrompt(system_prompt=criteria_prompt, user_message=user_prompt)
            llm_response = await self.llm_provider.call_async(llm_input, response_schema=RubricSchema)
            criteria = llm_response.parsed_answer
            self.criteria_cache[query.qid] = criteria
        self.answer_schema_cache[query.qid] = self._build_evaluation_schema(criteria)
        return criteria

    def _build_message(self, query: Query, answer: AgentAnswer) -> LLMInputPrompt:
        if query.qid not in self.answer_schema_cache:
            self.criteria_cache[query.qid] = call_async_fn(
                self._build_criteria, query, list(query.retrieved_docs.values())
            )
        criteria = self.criteria_cache[query.qid]
        system_prompt = self.system_prompt.render(
            expert_in=self.config.expert_in, criteria=criteria, company=self.config.company
        )
        user_prompt = self.user_prompt.render(query=query, answer=answer)
        return LLMInputPrompt(
            system_prompt=system_prompt,
            user_message=user_prompt,
            llm_response_schema=self.answer_schema_cache[query.qid],
        )

    def _process_answer(self, llm_response: LLMResponseType, query: Query) -> LLMResponseType:
        response_dict = llm_response.parsed_answer.model_dump()
        criteria: list[CriterionEvaluationPointwise] = []
        weighted_sum = 0.0
        total_weight = 0.0
        for crit, response in response_dict.items():
            crit_obj = [x for x in self.criteria_cache[query.qid].criteria if x.criterion_name == crit][0]
            criterion = CriterionEvaluationPointwise(
                criterion=crit_obj,
                reasoning=response["reasoning"],
                fulfillment=response["fulfillment"],
            )
            criteria.append(criterion)
            weighted_sum += response["fulfillment"] * (crit_obj.weight if crit_obj.weight is not None else 1.0)
            total_weight += crit_obj.weight if crit_obj.weight is not None else 1.0
        return LLMResponseType(
            raw_answer=llm_response.raw_answer,
            parsed_answer=RubricPointwiseAnswerFormat(
                criteria=criteria,
                average_score=weighted_sum / total_weight if total_weight > 0 else 0.0,
            ),
        )
