from typing import Literal, Type

from pydantic import BaseModel, Field, create_model

from ragelo.evaluators.answer_evaluators.base_answer_evaluator import AnswerEvaluatorFactory
from ragelo.evaluators.answer_evaluators.pairwise_evaluator import PairwiseAnswerEvaluator
from ragelo.types.answer_formats import CriterionEvaluation, RubricAnswerFormat, RubricSchema
from ragelo.types.configurations import RubricPairwiseEvaluatorConfig
from ragelo.types.evaluables import Document, PairwiseGame
from ragelo.types.formats import LLMInputPrompt, LLMResponseType
from ragelo.types.query import Query
from ragelo.types.types import AnswerEvaluatorTypes
from ragelo.utils import call_async_fn, string_to_template


@AnswerEvaluatorFactory.register(AnswerEvaluatorTypes.RUBRIC_PAIRWISE)
class RubricPairwiseEvaluator(PairwiseAnswerEvaluator):
    config: RubricPairwiseEvaluatorConfig
    criteria_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a set of relevant retrieved documents, create a rubric for evaluating the quality of reports generated by other agents.
        You should think deeply and carefully about what questions should a complete and high-quality report that answer the question should answer. 
        Each criterion should be a short yes/no question that can be used to evaluate the quality of the responses. 
        You should write {{ n_criteria }} criteria.
        If a criterion is supported by a document, you should include the document ID in the supporting_documents list for that criterion.
        """  # noqa: E501
    )

    criteria_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        [Retrieved Documents]
        {% for doc in documents %}
        [[{{doc.did}}]] {{doc.text}}
        --------------------------------
        {% endfor %}
        """)

    system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %} 
        You are tasked with evaluating the quality of two reports written by two deep research agents in response of a user's question.
        The reports are written based on a set of documents retrieved by the two agents, and should thoroughly answer the user's question based on the relevant documents retrieved by the agents.

        To properly evaluate the quality of the reports, you will be provided with a list of criteria to evaluate the quality of the responses. 
        Each criterion includes a short question and a list of documents that support the inclusion of the criterion in the report.
        For each criterion, you should think carefully about which of two answers better answers the criterion, and assign, for each criterion, one of the following values:

        - A if the report written by Agent A clearly answers the criterion better than the report written by     B
        - B if the report written by Agent B clearly answers the criterion better than the report written by Agent A.
        - C if the report written by Agent A and Agent B are equally good and answer the criterion equally well.
        - D if the report written by Agent A and Agent B are equally bad and neither answers the criterion.

        You should think carefully about the criteria and the answers, and assign the winner accordingly.

        ## Criteria
        {% for criteria in criteria.criteria %}
        Criterion: {{criteria.criterion_name}}
        Supporting Documents: {{criteria.supporting_documents}}
        Short Question: {{criteria.short_question}}
        --------------------------------
        {% endfor %}
        """  # noqa: E501
    )

    user_prompt = string_to_template("""
        [User Question]
            {{query.query}}

        [The Start of Agent A's Answer]
            {{ game.agent_a_answer.text }}
        [The End of Agent A's Answer]

        [The Start of Agent B's Answer]
            {{ game.agent_b_answer.text }}
        [The End of Agent B's Answer]""")

    criteria_cache: dict[str, RubricSchema] = {}

    answer_schema_cache: dict[str, Type[BaseModel]] = {}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.config.rubrics:
            self.criteria_cache = {qid: RubricSchema(criteria=rubrics) for qid, rubrics in self.config.rubrics.items()}
        else:
            self.criteria_cache = {}

    def _build_evaluation_schema(self, criteria: RubricSchema) -> Type[BaseModel]:
        criteria_models = {}
        for criterion in criteria.criteria:
            criteria_models[criterion.criterion_name] = create_model(
                criterion.criterion_name,
                reasoning=(
                    str,
                    Field(description="A brief explanation about your judgement, and why you chose the winner"),
                ),
                winner=(Literal["A", "B", "C", "D"], Field(description="The winner of the criterion")),
            )
        return create_model("EvaluationSchema", **criteria_models)  # type: ignore[call-overload]

    async def _build_criteria(self, query: Query, documents: list[Document]) -> Type[BaseModel]:
        if query.qid in self.criteria_cache:
            criteria = self.criteria_cache[query.qid]
        else:
            documents = self._filter_documents(query)
            context = {
                "expert_in": self.config.expert_in,
                "company": self.config.company,
                "documents": documents,
                "query": query,
                "n_criteria": self.config.n_criteria,
            }
            criteria_prompt = self.criteria_prompt.render(context)
            user_prompt = self.criteria_user_prompt.render(context)
            llm_input = LLMInputPrompt(system_prompt=criteria_prompt, user_message=user_prompt)
            llm_response = await self.llm_provider.call_async(llm_input, response_schema=RubricSchema)
            criteria = llm_response.parsed_answer
            self.criteria_cache[query.qid] = criteria
        evaluation_schema = self._build_evaluation_schema(criteria)
        return evaluation_schema

    def _build_message_pairwise(self, query: Query, game: PairwiseGame) -> LLMInputPrompt:
        llm_response_schema = call_async_fn(self._build_criteria, query, list(query.retrieved_docs.values()))
        criteria = self.criteria_cache[query.qid]
        system_prompt = self.system_prompt.render(
            expert_in=self.config.expert_in, criteria=criteria, company=self.config.company
        )
        user_prompt = self.user_prompt.render(
            query=query,
            game=game,
        )
        return LLMInputPrompt(
            system_prompt=system_prompt, user_message=user_prompt, llm_response_schema=llm_response_schema
        )

    def _process_answer(self, llm_response: LLMResponseType, query: Query) -> LLMResponseType:
        response_dict = llm_response.parsed_answer.model_dump()
        agent_a_wins = 0
        agent_b_wins = 0
        equally_good = 0
        equally_bad = 0
        criteria: list[CriterionEvaluation] = []

        for crit, response in response_dict.items():
            crit_obj = [x for x in self.criteria_cache[query.qid].criteria if x.criterion_name == crit][0]
            if len(response["winner"]) > 1:
                response["winner"] = response["winner"][-1]
            if response["winner"] == "D":
                response["winner"] = "C"
            criterion = CriterionEvaluation(
                criterion=crit_obj,
                reasoning=response["reasoning"],
                winner=response["winner"],
            )
            criteria.append(criterion)
            if response["winner"] == "A":
                agent_a_wins += 1
            elif response["winner"] == "B":
                agent_b_wins += 1
            elif response["winner"] == "C":
                equally_good += 1
            else:
                equally_bad += 1
        winner = "A" if agent_a_wins > agent_b_wins else "B" if agent_a_wins < agent_b_wins else "C"
        parsed_answer = RubricAnswerFormat(
            criteria=criteria,
            agent_a_wins=agent_a_wins,
            agent_b_wins=agent_b_wins,
            equally_good=equally_good,
            equally_bad=equally_bad,
            winner=winner,
        )

        return LLMResponseType(
            raw_answer=llm_response.raw_answer,
            parsed_answer=parsed_answer,
        )
