from __future__ import annotations

from typing import Literal, Type

from pydantic import BaseModel, Field, create_model

from ragelo.evaluators.answer_evaluators.base_answer_evaluator import AnswerEvaluatorFactory
from ragelo.evaluators.answer_evaluators.pairwise_evaluator import PairwiseAnswerEvaluator
from ragelo.types.answer_formats import CriterionEvaluation, RubricAnswerFormat, RubricSchema
from ragelo.types.configurations import RubricPairwiseEvaluatorConfig
from ragelo.types.evaluables import Document, PairwiseGame
from ragelo.types.formats import LLMInputPrompt, LLMResponseType
from ragelo.types.query import Query
from ragelo.types.types import AnswerEvaluatorTypes
from ragelo.utils import call_async_fn, string_to_template


@AnswerEvaluatorFactory.register(AnswerEvaluatorTypes.RUBRIC_PAIRWISE)
class RubricPairwiseEvaluator(PairwiseAnswerEvaluator):
    config: RubricPairwiseEvaluatorConfig
    criteria_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a set of relevant retrieved documents, create a rubric for evaluating the quality of reports generated by other agents.
        You should think deeply and carefully about what questions should a complete and high-quality report that answer the question should answer. 
        Each criterion should be a short yes/no question that can be used to evaluate the quality of the responses. 
        You should write {{ n_criteria }} criteria.
        If a criterion is supported by a document, you should include the document ID in the supporting_documents list for that criterion.
        You may optionally assign a weight (a positive number) to each criterion to indicate its relative importance. More important criteria should have higher weights. If no weight is provided, all criteria are weighted equally.
        """  # noqa: E501
    )

    criteria_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        [Retrieved Documents]
        {% for doc in documents %}
        [[{{doc.did}}]] {{doc.text}}
        --------------------------------
        {% endfor %}
        """)

    system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %} 
        You are tasked with evaluating the quality of two reports written by two deep research agents in response of a user's question.
        The reports are written based on a set of documents retrieved by the two agents, and should thoroughly answer the user's question based on the relevant documents retrieved by the agents.

        To properly evaluate the quality of the reports, you will be provided with a list of criteria to evaluate the quality of the responses. 
        Each criterion includes a short question, an optional weight indicating its relative importance, and a list of documents that support the inclusion of the criterion in the report.
        For each criterion, you should think carefully about which of two answers better answers the criterion, and assign, for each criterion, one of the following values:

        - A if the report written by Agent A clearly answers the criterion better than the report written by     B
        - B if the report written by Agent B clearly answers the criterion better than the report written by Agent A.
        - C if the report written by Agent A and Agent B are equally good and answer the criterion equally well.
        - D if the report written by Agent A and Agent B are equally bad and neither answers the criterion.

        You should think carefully about the criteria and the answers, and assign the winner accordingly.

        ## Output Constraints
        - In any free-text field, refer to the reports only as [[A]] and [[B]].
        - Do not use phrases such as first answer, second answer, former, latter, this answer, or that answer.
        - For each criterion, provide a side-specific assessment for [[A]], a side-specific assessment for [[B]], and a brief winner_reasoning.

        ## Criteria
        {% for criteria in criteria.criteria %}
        Criterion: {{criteria.criterion_name}}
        {% if criteria.weight is not none %}Weight: {{criteria.weight}}
        {% endif %}Supporting Documents: {{criteria.supporting_documents}}
        Short Question: {{criteria.short_question}}
        --------------------------------
        {% endfor %}
        """  # noqa: E501
    )

    user_prompt = string_to_template("""
        [User Question]
            {{query.query}}

        [The Start of Agent A's Answer]
            {{ game.agent_a_answer.text }}
        [The End of Agent A's Answer]

        [The Start of Agent B's Answer]
            {{ game.agent_b_answer.text }}
        [The End of Agent B's Answer]""")

    criteria_cache: dict[str, RubricSchema]
    answer_schema_cache: dict[str, Type[BaseModel]]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.config.rubrics:
            self.criteria_cache = {qid: RubricSchema(criteria=rubrics) for qid, rubrics in self.config.rubrics.items()}
        else:
            self.criteria_cache = {}
        self.answer_schema_cache = {}

    def _build_evaluation_schema(self, criteria: RubricSchema) -> Type[BaseModel]:
        criteria_models = {}
        for criterion in criteria.criteria:
            criteria_models[criterion.criterion_name] = create_model(
                criterion.criterion_name,
                agent_a_assessment=(str, Field(description="How well [[A]] satisfies the criterion.")),
                agent_b_assessment=(str, Field(description="How well [[B]] satisfies the criterion.")),
                winner_reasoning=(str, Field(description="A brief explanation of why the winner was chosen.")),
                reasoning=(
                    str,
                    Field(description="A brief explanation about your judgement, and why you chose the winner"),
                ),
                winner=(Literal["A", "B", "C", "D"], Field(description="The winner of the criterion")),
            )
        return create_model("EvaluationSchema", **criteria_models)  # type: ignore[call-overload]

    async def _build_criteria(self, query: Query, documents: list[Document]) -> RubricSchema:
        if query.qid in self.criteria_cache:
            criteria = self.criteria_cache[query.qid]
        else:
            documents = self._filter_documents(query)
            context = {
                "expert_in": self.config.expert_in,
                "company": self.config.company,
                "documents": documents,
                "query": query,
                "n_criteria": self.config.n_criteria,
            }
            criteria_prompt = self.criteria_prompt.render(context)
            user_prompt = self.criteria_user_prompt.render(context)
            llm_input = LLMInputPrompt(system_prompt=criteria_prompt, user_message=user_prompt)
            llm_response = await self.llm_provider.call_async(llm_input, response_schema=RubricSchema)
            criteria = llm_response.parsed_answer
            self.criteria_cache[query.qid] = criteria
        self.answer_schema_cache[query.qid] = self._build_evaluation_schema(criteria)
        return criteria

    def _build_message_pairwise(self, query: Query, game: PairwiseGame) -> LLMInputPrompt:
        if query.qid not in self.answer_schema_cache:
            call_async_fn(self._build_criteria, query, list(query.retrieved_docs.values()))
        criteria = self.criteria_cache[query.qid]
        system_prompt = self.system_prompt.render(
            expert_in=self.config.expert_in, criteria=criteria, company=self.config.company
        )
        user_prompt = self.user_prompt.render(
            query=query,
            game=game,
        )
        return LLMInputPrompt(
            system_prompt=system_prompt,
            user_message=user_prompt,
            llm_response_schema=self.answer_schema_cache[query.qid],
        )

    def _process_answer(self, llm_response: LLMResponseType, query: Query) -> LLMResponseType:
        response_dict = llm_response.parsed_answer.model_dump()
        agent_a_wins = 0.0
        agent_b_wins = 0.0
        equally_good = 0.0
        equally_bad = 0.0
        criteria: list[CriterionEvaluation] = []

        for crit, response in response_dict.items():
            crit_obj = [x for x in self.criteria_cache[query.qid].criteria if x.criterion_name == crit][0]
            weight = crit_obj.weight if crit_obj.weight is not None else 1.0
            if len(response["winner"]) > 1:
                response["winner"] = response["winner"][-1]
            if response["winner"] == "D":
                response["winner"] = "C"
            agent_a_assessment = response.get("agent_a_assessment", "")
            agent_b_assessment = response.get("agent_b_assessment", "")
            winner_reasoning = response.get("winner_reasoning", response.get("reasoning", ""))
            criterion = CriterionEvaluation(
                criterion=crit_obj,
                agent_a_assessment=agent_a_assessment,
                agent_b_assessment=agent_b_assessment,
                winner_reasoning=winner_reasoning,
                reasoning=response.get("reasoning", winner_reasoning),
                winner=response["winner"],
            )
            criteria.append(criterion)
            if response["winner"] == "A":
                agent_a_wins += weight
            elif response["winner"] == "B":
                agent_b_wins += weight
            elif response["winner"] == "C":
                equally_good += weight
            else:
                equally_bad += weight
        winner = "A" if agent_a_wins > agent_b_wins else "B" if agent_a_wins < agent_b_wins else "C"
        parsed_answer = RubricAnswerFormat(
            criteria=criteria,
            agent_a_wins=agent_a_wins,
            agent_b_wins=agent_b_wins,
            equally_good=equally_good,
            equally_bad=equally_bad,
            winner=winner,
        )

        return LLMResponseType(
            raw_answer=llm_response.raw_answer,
            parsed_answer=parsed_answer,
        )
