from __future__ import annotations

from typing import Literal, Type

from pydantic import BaseModel, Field, create_model

from ragelo.evaluators.answer_evaluators.base_answer_evaluator import AnswerEvaluatorFactory
from ragelo.evaluators.answer_evaluators.builtin_criteria import (
    evaluate_citation_quality,
    evaluate_evidence_recall,
    get_evidence_snippets,
)
from ragelo.evaluators.answer_evaluators.pairwise_evaluator import PairwiseAnswerEvaluator
from ragelo.types.answer_formats import CriterionEvaluation, RubricAnswerFormat, RubricSchema
from ragelo.types.configurations import RubricPairwiseEvaluatorConfig
from ragelo.types.evaluables import ChatMessage, Document, Evaluable, PairwiseGame
from ragelo.types.formats import LLMInputPrompt, LLMResponseType
from ragelo.types.query import Query
from ragelo.types.results import AnswerEvaluatorResult, PairwiseGameEvaluatorResult
from ragelo.types.types import AnswerEvaluatorTypes
from ragelo.utils import string_to_template


@AnswerEvaluatorFactory.register(AnswerEvaluatorTypes.RUBRIC_PAIRWISE)
class RubricPairwiseEvaluator(PairwiseAnswerEvaluator):
    config: RubricPairwiseEvaluatorConfig
    criteria_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a set of relevant retrieved documents, create a rubric for evaluating the quality of reports generated by other agents.
        You should think deeply and carefully about what questions should a complete and high-quality report that answer the question should answer. 
        Each criterion should be a short yes/no question that can be used to evaluate the quality of the responses. 
        You should write {{ n_criteria }} criteria.
        If a criterion is supported by a document, you should include the document ID in the evidence list for that criterion.
        You may optionally assign a weight (a positive number) to each criterion to indicate its relative importance. More important criteria should have higher weights. If no weight is provided, all criteria are weighted equally.
        """  # noqa: E501
    )

    criteria_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        {% if conversation_context %}
        [Conversation Context]
        {% for msg in conversation_context %}
        {{ msg }}
        {% endfor %}
        {% endif %}

        [Retrieved Documents]
        {% for doc in documents %}
        [[{{doc.did}}]] {{doc.text}}
        --------------------------------
        {% endfor %}
        """)

    system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %} 
        You are tasked with evaluating the quality of two {% if is_conversation %}conversations{% else %}reports{% endif %} written by two agents in response of a user's question.
        The {% if is_conversation %}conversations{% else %}reports{% endif %} are written based on a set of documents retrieved by the two agents, and should answer the user's question based on the relevant documents retrieved by the agents.

        To properly evaluate the quality of the {% if is_conversation %}conversations{% else %}reports{% endif %}, you will be provided with a list of criteria to evaluate the quality of the responses. 
        Each criterion includes a short question and an optional list of documents that support the inclusion of the criterion in the {% if is_conversation %}conversation{% else %}report{% endif %}.
        For each criterion, you should think carefully about which of two answers better answers the criterion, and provide the following:

        ### Winner
        Assign one of the following values:
        - A if the {% if is_conversation %}conversation{% else %}report{% endif %} written by Agent A clearly answers the criterion better than the {% if is_conversation %}conversation{% else %}report{% endif %} written by Agent B.
        - B if the {% if is_conversation %}conversation{% else %}report{% endif %} written by Agent B clearly answers the criterion better than the {% if is_conversation %}conversation{% else %}report{% endif %} written by Agent A.
        - C if the {% if is_conversation %}conversation{% else %}report{% endif %} written by Agent A and Agent B are equally good and answer the criterion equally well.
        {% if preserve_d %}- D if the {% if is_conversation %}conversation{% else %}report{% endif %} written by Agent A and Agent B are equally bad and neither answers the criterion.
        {% endif %}
        {% if rich_output %}
        ### Scores
        - `score_a`: Rate how well [[A]] satisfies this criterion from 0.0 (not at all) to 1.0 (fully).
        - `score_b`: Rate how well [[B]] satisfies this criterion from 0.0 (not at all) to 1.0 (fully).

        ### Diagnostics
        - `loser_fix`: A concise, actionable suggestion for how the losing answer could improve on this criterion. If tied{% if preserve_d %} (C or D){% endif %}, leave empty.
        - `failure_tags`: Tag the loser's weaknesses using zero or more of: `missing_evidence`, `unsupported_claim`, `incomplete_coverage`, `poor_synthesis`, `citation_error`, `verbosity_without_content`. If tied, leave empty.
        - `confidence`: Your confidence in this criterion's verdict from 0.0 (very uncertain) to 1.0 (certain).
        {% endif %}
        {% if include_evidence %}

        ### Evidence Assessment
        - `missing_evidence_doc_ids`: List any document IDs from the supporting documents that the loser failed to use.
        - `missing_evidence_snippets`: List specific evidence snippets from the supporting documents that the loser omitted or misused.
        {% endif %}

        ## Output Constraints
        - In any free-text field, refer to the reports only as [[A]] and [[B]].
        - Do not use phrases such as first answer, second answer, former, latter, this answer, or that answer.
        - For each criterion, provide a side-specific assessment for [[A]], a side-specific assessment for [[B]], and a brief winner_reasoning.

        {% if evidence_snippets %}
        ## Evidence Snippets
        The following evidence snippets were extracted from the retrieved documents. Use them to assess whether each answer correctly leverages the available evidence.
        {% for snippet in evidence_snippets %}
        - {{ snippet }}
        {% endfor %}
        {% endif %}

        ## Criteria
        {% for criteria in criteria.criteria %}
        Criterion: {{criteria.criterion_name}}
        Supporting Documents: {{criteria.evidence}}
        Short Question: {{criteria.short_question}}
        --------------------------------
        {% endfor %}
        """  # noqa: E501
    )

    user_prompt = string_to_template("""
        [User Question]
            {{query.query}}

        [The Start of Agent A's Answer]
        {% if game.agent_a_answer.conversation %}
        {% for msg in game.agent_a_answer.conversation %}
        {{ msg }}
        {% endfor %}
        {% else %}
            {{ game.agent_a_answer.text }}
        {% endif %}
        [The End of Agent A's Answer]

        [The Start of Agent B's Answer]
        {% if game.agent_b_answer.conversation %}
        {% for msg in game.agent_b_answer.conversation %}
        {{ msg }}
        {% endfor %}
        {% else %}
            {{ game.agent_b_answer.text }}
        {% endif %}
        [The End of Agent B's Answer]""")

    criteria_cache: dict[str, RubricSchema]
    answer_schema_cache: dict[str, Type[BaseModel]]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.answer_schema_cache = {}
        if self.config.rubrics:
            self.criteria_cache = {qid: RubricSchema(criteria=rubrics) for qid, rubrics in self.config.rubrics.items()}
            for qid, criteria in self.criteria_cache.items():
                self.answer_schema_cache[qid] = self._build_evaluation_schema(criteria)
        else:
            self.criteria_cache = {}

    def _build_evaluation_schema(self, criteria: RubricSchema) -> Type[BaseModel]:
        include_evidence = self.config.include_evidence_in_evaluation
        rich_output = self.config.rich_pairwise_output
        preserve_d = self.config.preserve_d
        winner_type = Literal["A", "B", "C", "D"] if preserve_d else Literal["A", "B", "C"]
        criteria_models = {}
        for criterion in criteria.criteria:
            fields: dict = {
                "agent_a_assessment": (str, Field(description="How well [[A]] satisfies the criterion.")),
                "agent_b_assessment": (str, Field(description="How well [[B]] satisfies the criterion.")),
                "winner_reasoning": (str, Field(description="A brief explanation of why the winner was chosen.")),
                "winner": (winner_type, Field(description="The winner of the criterion")),
            }
            if rich_output:
                fields.update(
                    {
                        "score_a": (float, Field(description="Score for [[A]] on this criterion (0.0 to 1.0).")),
                        "score_b": (float, Field(description="Score for [[B]] on this criterion (0.0 to 1.0).")),
                        "loser_fix": (
                            str,
                            Field(
                                description="One sentence: what should the losing side do differently? Empty if tied."
                            ),
                        ),
                        "failure_tags": (
                            list[str],
                            Field(
                                description="Tags from: missing_evidence, unsupported_claim, incomplete_coverage, "
                                "poor_synthesis, citation_error, verbosity_without_content. Empty if tied."
                            ),
                        ),
                        "confidence": (float, Field(description="Your confidence in this verdict, 0.0 to 1.0.")),
                    }
                )
            if include_evidence:
                fields["missing_evidence_doc_ids"] = (
                    list[str],
                    Field(description="Document IDs the loser failed to use."),
                )
                fields["missing_evidence_snippets"] = (
                    list[str],
                    Field(description="Evidence snippets the loser omitted or misused."),
                )
            criteria_models[criterion.criterion_name] = create_model(criterion.criterion_name, **fields)
        return create_model("EvaluationSchema", **criteria_models)  # type: ignore[call-overload]

    async def _build_criteria(
        self,
        query: Query,
        documents: list[Document],
        conversation_context: list[ChatMessage] | None = None,
    ) -> RubricSchema:
        if query.qid in self.criteria_cache:
            criteria = self.criteria_cache[query.qid]
        else:
            documents = self._filter_documents(query)
            context = {
                "expert_in": self.config.expert_in,
                "company": self.config.company,
                "documents": documents,
                "conversation_context": conversation_context or [],
                "query": query,
                "n_criteria": self.config.n_criteria,
            }
            criteria_prompt = self.criteria_prompt.render(**context)
            user_prompt = self.criteria_user_prompt.render(**context)
            llm_input = LLMInputPrompt(system_prompt=criteria_prompt, user_message=user_prompt)
            llm_response = await self.llm_provider.call_async(llm_input, response_schema=RubricSchema)
            criteria = llm_response.parsed_answer
            self.criteria_cache[query.qid] = criteria
        self.answer_schema_cache[query.qid] = self._build_evaluation_schema(criteria)
        return criteria

    def _build_message_pairwise(self, query: Query, game: PairwiseGame) -> LLMInputPrompt:
        if query.qid not in self.answer_schema_cache:
            raise RuntimeError(
                f"Rubric for qid={query.qid} has not been built. "
                "evaluate_async() must be called, which awaits _build_criteria() before _build_message_pairwise()."
            )
        criteria = self.criteria_cache[query.qid]
        include_evidence = self.config.include_evidence_in_evaluation
        evidence_snippets: list[str] = []
        is_conversation = bool(game.agent_a_answer.conversation or game.agent_b_answer.conversation)
        if include_evidence:
            evidence_snippets = get_evidence_snippets(query, self.config.evidence_snippets, self.criteria_cache)
            evidence_snippets = _truncate_snippets(evidence_snippets, self.config.max_evidence_tokens)
        system_prompt = self.system_prompt.render(
            expert_in=self.config.expert_in,
            criteria=criteria,
            company=self.config.company,
            include_evidence=include_evidence,
            is_conversation=is_conversation,
            evidence_snippets=evidence_snippets,
            preserve_d=self.config.preserve_d,
            rich_output=self.config.rich_pairwise_output,
        )
        user_prompt = self.user_prompt.render(
            query=query,
            game=game,
        )
        return LLMInputPrompt(
            system_prompt=system_prompt,
            user_message=user_prompt,
            llm_response_schema=self.answer_schema_cache[query.qid],
        )

    def _process_answer(self, llm_response: LLMResponseType, query: Query) -> LLMResponseType:
        response_dict = llm_response.parsed_answer.model_dump()
        preserve_d = self.config.preserve_d
        agent_a_wins = 0.0
        agent_b_wins = 0.0
        equally_good = 0.0
        equally_bad = 0.0
        total_confidence = 0.0
        criteria: list[CriterionEvaluation] = []

        for crit, response in response_dict.items():
            crit_obj = [x for x in self.criteria_cache[query.qid].criteria if x.criterion_name == crit][0]
            weight = crit_obj.weight if crit_obj.weight is not None else 1.0
            if len(response["winner"]) > 1:
                response["winner"] = response["winner"][-1]
            if not preserve_d and response["winner"] == "D":
                response["winner"] = "C"
            agent_a_assessment = response.get("agent_a_assessment", "")
            agent_b_assessment = response.get("agent_b_assessment", "")
            winner_reasoning = response.get("winner_reasoning", response.get("reasoning", ""))
            confidence = response.get("confidence", 1.0)
            total_confidence += confidence
            criterion = CriterionEvaluation(
                criterion=crit_obj,
                agent_a_assessment=agent_a_assessment,
                agent_b_assessment=agent_b_assessment,
                winner_reasoning=winner_reasoning,
                winner=response["winner"],
                score_a=response.get("score_a", 0.0),
                score_b=response.get("score_b", 0.0),
                loser_fix=response.get("loser_fix", ""),
                failure_tags=response.get("failure_tags", []),
                confidence=confidence,
                missing_evidence_doc_ids=response.get("missing_evidence_doc_ids", []),
                missing_evidence_snippets=response.get("missing_evidence_snippets", []),
            )
            criteria.append(criterion)
            if response["winner"] == "A":
                agent_a_wins += weight
            elif response["winner"] == "B":
                agent_b_wins += weight
            elif response["winner"] == "C":
                equally_good += weight
            else:
                equally_bad += weight
        winner = "A" if agent_a_wins > agent_b_wins else "B" if agent_a_wins < agent_b_wins else "C"
        n_criteria = len(criteria) or 1
        parsed_answer = RubricAnswerFormat(
            criteria=criteria,
            agent_a_wins=agent_a_wins,
            agent_b_wins=agent_b_wins,
            equally_good=equally_good,
            equally_bad=equally_bad,
            winner=winner,
            margin=agent_a_wins - agent_b_wins,
            mean_confidence=total_confidence / n_criteria,
        )

        return LLMResponseType(
            raw_answer=llm_response.raw_answer,
            parsed_answer=parsed_answer,
        )

    async def evaluate_async(
        self, eval_sample: tuple[Query, Evaluable]
    ) -> AnswerEvaluatorResult | PairwiseGameEvaluatorResult:
        query, evaluable = eval_sample
        if isinstance(evaluable, PairwiseGame) and query.qid not in self.answer_schema_cache:
            conversation_context = self._get_shared_conversation_context(evaluable)
            await self._build_criteria(query, list(query.retrieved_docs.values()), conversation_context)

        result = await super().evaluate_async(eval_sample)
        if not isinstance(result, PairwiseGameEvaluatorResult) or result.answer is None or result.exception:
            return result

        if not isinstance(evaluable, PairwiseGame):
            return result

        answer_format = result.answer
        if not isinstance(answer_format, RubricAnswerFormat):
            return result

        if not self.config.evidence_recall and not self.config.citation_quality:
            return result

        agent_a_text = evaluable.agent_a_answer.final_response
        agent_b_text = evaluable.agent_b_answer.final_response
        snippets = get_evidence_snippets(query, self.config.evidence_snippets, self.criteria_cache)
        relevant_doc_ids = list(query.retrieved_docs.keys())
        agent_a_wins = answer_format.agent_a_wins
        agent_b_wins = answer_format.agent_b_wins
        equally_good = answer_format.equally_good
        updates: dict = {}

        if self.config.evidence_recall:
            recall_a = await evaluate_evidence_recall(self.llm_provider, agent_a_text, snippets)
            recall_b = await evaluate_evidence_recall(self.llm_provider, agent_b_text, snippets)
            updates["evidence_recall_a"] = recall_a
            updates["evidence_recall_b"] = recall_b
            weight = self.config.evidence_recall_weight
            if recall_a.recall > recall_b.recall:
                agent_a_wins += weight
            elif recall_b.recall > recall_a.recall:
                agent_b_wins += weight
            else:
                equally_good += weight

        if self.config.citation_quality:
            cq_a = await evaluate_citation_quality(self.llm_provider, agent_a_text, relevant_doc_ids)
            cq_b = await evaluate_citation_quality(self.llm_provider, agent_b_text, relevant_doc_ids)
            updates["citation_quality_a"] = cq_a
            updates["citation_quality_b"] = cq_b
            score_a = (cq_a.claims_with_citations_ratio + cq_a.citations_with_excerpts_ratio) / 2.0
            score_b = (cq_b.claims_with_citations_ratio + cq_b.citations_with_excerpts_ratio) / 2.0
            weight = self.config.citation_quality_weight
            if score_a > score_b:
                agent_a_wins += weight
            elif score_b > score_a:
                agent_b_wins += weight
            else:
                equally_good += weight

        winner = "A" if agent_a_wins > agent_b_wins else "B" if agent_a_wins < agent_b_wins else "C"
        updates.update(
            {
                "agent_a_wins": agent_a_wins,
                "agent_b_wins": agent_b_wins,
                "equally_good": equally_good,
                "winner": winner,
                "margin": agent_a_wins - agent_b_wins,
            }
        )
        updated_answer = answer_format.model_copy(update=updates)
        return result.model_copy(update={"answer": updated_answer})


def _truncate_snippets(snippets: list[str], max_chars: int) -> list[str]:
    result = []
    total = 0
    for s in snippets:
        if total + len(s) > max_chars:
            remaining = max_chars - total
            if remaining > 50:
                result.append(s[:remaining])
            break
        result.append(s)
        total += len(s)
    return result
