from __future__ import annotations

from typing import Type

from pydantic import BaseModel, Field, create_model

from ragelo.evaluators.answer_evaluators.base_answer_evaluator import AnswerEvaluatorFactory, BaseAnswerEvaluator
from ragelo.evaluators.answer_evaluators.builtin_criteria import (
    evaluate_citation_quality,
    evaluate_evidence_recall,
    get_evidence_snippets,
)
from ragelo.types.answer_formats import CriterionEvaluationPointwise, RubricPointwiseAnswerFormat, RubricSchema
from ragelo.types.configurations import RubricPointwiseEvaluatorConfig
from ragelo.types.evaluables import AgentAnswer, Document, Evaluable
from ragelo.types.formats import LLMInputPrompt, LLMResponseType
from ragelo.types.query import Query
from ragelo.types.results import AnswerEvaluatorResult, PairwiseGameEvaluatorResult
from ragelo.types.types import AnswerEvaluatorTypes
from ragelo.utils import call_async_fn, string_to_template


@AnswerEvaluatorFactory.register(AnswerEvaluatorTypes.RUBRIC_POINTWISE)
class RubricPointwiseEvaluator(BaseAnswerEvaluator[RubricPointwiseEvaluatorConfig, AnswerEvaluatorResult]):
    config: RubricPointwiseEvaluatorConfig
    result_type = AnswerEvaluatorResult

    criteria_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %}
        Your task is to, given a user question and a set of relevant retrieved documents, create a rubric for evaluating the quality of reports generated by other agents.
        You should think deeply and carefully about what questions should a complete and high-quality report that answer the question should answer. 
        Each criterion should be a short yes/no question that can be used to evaluate the quality of the responses. 
        You should write {{ n_criteria }} criteria.
        If a criterion is supported by a document, you should include the document ID in the supporting_documents list for that criterion.
        You may optionally assign a weight (a positive number) to each criterion to indicate its relative importance. More important criteria should have higher weights. If no weight is provided, all criteria are weighted equally.
        """  # noqa: E501
    )

    criteria_user_prompt = string_to_template("""
        [User Question]
        {{ query.query }}

        [Retrieved Documents]
        {% for doc in documents %}
        [[{{doc.did}}]] {{doc.text}}
        --------------------------------
        {% endfor %}
        """)

    system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %} 
        You are tasked with evaluating the quality of a report written by a deep research agent in response of a user's question.
        The report was written based on a set of documents retrieved by the agent, and should thoroughly answer the user's question based exclusively on the relevant documents retrieved by the agent.

        To properly evaluate the quality of the report, you will be provided with a list of criteria to evaluate its quality.
        Each criterion includes a short question, an optional weight indicating its relative importance, and a list of documents that support the inclusion of the criterion in the report.
        For each criterion, you should think carefully about wether the report answers the criterion, and include a brief reasoning for your decision.

        You should think carefully about the criteria and the answers, and assign the final judgement accordingly.

        ## Criteria
        {% for criteria in criteria.criteria %}
        Criterion: {{criteria.criterion_name}}
        {% if criteria.weight is not none %}Weight: {{criteria.weight}}
        {% endif %}Supporting Documents: {{criteria.supporting_documents}}
        Short Question: {{criteria.short_question}}
        --------------------------------
        {% endfor %}
        """  # noqa: E501
    )

    graduated_system_prompt = string_to_template(
        """
        You are a domain expert in {{ expert_in }}.{% if company %} You work for {{ company }}.{% endif %} 
        You are tasked with evaluating the quality of a report written by a deep research agent in response of a user's question.
        The report was written based on a set of documents retrieved by the agent, and should thoroughly answer the user's question based exclusively on the relevant documents retrieved by the agent.

        To properly evaluate the quality of the report, you will be provided with a list of criteria to evaluate its quality.
        Each criterion includes a short question, an optional weight indicating its relative importance, and a list of documents that support the inclusion of the criterion in the report.
        For each criterion, you should think carefully about how well the report addresses the criterion, provide a brief reasoning, and assign a score from 0 to {{ max_score }}, where 0 means the criterion is not addressed at all and {{ max_score }} means it is fully and thoroughly addressed.

        You should think carefully about the criteria and the answers, and assign the scores accordingly.

        ## Criteria
        {% for criteria in criteria.criteria %}
        Criterion: {{criteria.criterion_name}}
        {% if criteria.weight is not none %}Weight: {{criteria.weight}}
        {% endif %}Supporting Documents: {{criteria.supporting_documents}}
        Short Question: {{criteria.short_question}}
        --------------------------------
        {% endfor %}
        """  # noqa: E501
    )

    user_prompt = string_to_template("""
        [User Question]
            {{query.query}}

        [Agent's Report]
            {{ answer.text }}
        """)

    criteria_cache: dict[str, RubricSchema]
    answer_schema_cache: dict[str, Type[BaseModel]]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.config.rubrics:
            self.criteria_cache = {qid: RubricSchema(criteria=rubrics) for qid, rubrics in self.config.rubrics.items()}
        else:
            self.criteria_cache = {}
        self.answer_schema_cache = {}

    def _build_evaluation_schema(self, criteria: RubricSchema) -> Type[BaseModel]:
        criteria_models = {}
        for criterion in criteria.criteria:
            if self.config.graduated_scoring:
                criteria_models[criterion.criterion_name] = create_model(
                    criterion.criterion_name,
                    reasoning=(
                        str,
                        Field(
                            description="A brief explanation about your judgement, "
                            "and why you believe the report fulfills or not the criterion"
                        ),
                    ),
                    score=(
                        int,
                        Field(
                            description=f"Score from 0 to {self.config.max_score}. "
                            f"0 means not addressed at all, {self.config.max_score} means fully addressed.",
                            ge=0,
                            le=self.config.max_score,
                        ),
                    ),
                )
            else:
                criteria_models[criterion.criterion_name] = create_model(
                    criterion.criterion_name,
                    reasoning=(
                        str,
                        Field(
                            description="A brief explanation about your judgement, "
                            "and why you believe the report fulfills or not the criterion"
                        ),
                    ),
                    fulfillment=(
                        bool,
                        Field(description="Whether the report fulfills the criterion or not"),
                    ),
                )
        return create_model("EvaluationSchema", **criteria_models)  # type: ignore[call-overload]

    async def _build_criteria(self, query: Query, documents: list[Document]) -> RubricSchema:
        if query.qid in self.criteria_cache:
            criteria = self.criteria_cache[query.qid]
        else:
            documents = self._filter_documents(query)
            context = {
                "expert_in": self.config.expert_in,
                "company": self.config.company,
                "documents": documents,
                "query": query,
                "n_criteria": self.config.n_criteria,
            }
            criteria_prompt = self.criteria_prompt.render(context)
            user_prompt = self.criteria_user_prompt.render(context)
            llm_input = LLMInputPrompt(system_prompt=criteria_prompt, user_message=user_prompt)
            llm_response = await self.llm_provider.call_async(llm_input, response_schema=RubricSchema)
            criteria = llm_response.parsed_answer
            self.criteria_cache[query.qid] = criteria
        self.answer_schema_cache[query.qid] = self._build_evaluation_schema(criteria)
        return criteria

    def _build_message(self, query: Query, answer: AgentAnswer) -> LLMInputPrompt:
        if query.qid not in self.answer_schema_cache:
            self.criteria_cache[query.qid] = call_async_fn(
                self._build_criteria, query, list(query.retrieved_docs.values())
            )
        criteria = self.criteria_cache[query.qid]
        prompt_template = self.graduated_system_prompt if self.config.graduated_scoring else self.system_prompt
        system_prompt = prompt_template.render(
            expert_in=self.config.expert_in,
            criteria=criteria,
            company=self.config.company,
            max_score=self.config.max_score,
        )
        user_prompt = self.user_prompt.render(query=query, answer=answer)
        return LLMInputPrompt(
            system_prompt=system_prompt,
            user_message=user_prompt,
            llm_response_schema=self.answer_schema_cache[query.qid],
        )

    def _process_answer(self, llm_response: LLMResponseType, query: Query) -> LLMResponseType:
        response_dict = llm_response.parsed_answer.model_dump()
        criteria: list[CriterionEvaluationPointwise] = []
        weighted_sum = 0.0
        total_weight = 0.0
        for crit, response in response_dict.items():
            crit_obj = [x for x in self.criteria_cache[query.qid].criteria if x.criterion_name == crit][0]
            weight = crit_obj.weight if crit_obj.weight is not None else 1.0
            if self.config.graduated_scoring:
                raw_score = response["score"]
                normalized = raw_score / self.config.max_score
                fulfillment: bool | float = normalized
            else:
                fulfillment = response["fulfillment"]
                normalized = float(fulfillment)
            criterion = CriterionEvaluationPointwise(
                criterion=crit_obj,
                reasoning=response["reasoning"],
                fulfillment=fulfillment,
            )
            criteria.append(criterion)
            weighted_sum += normalized * weight
            total_weight += weight
        return LLMResponseType(
            raw_answer=llm_response.raw_answer,
            parsed_answer=RubricPointwiseAnswerFormat(
                criteria=criteria,
                average_score=weighted_sum / total_weight if total_weight > 0 else 0.0,
            ),
        )

    async def evaluate_async(
        self, eval_sample: tuple[Query, Evaluable]
    ) -> AnswerEvaluatorResult | PairwiseGameEvaluatorResult:
        result = await super().evaluate_async(eval_sample)
        if not isinstance(result, AnswerEvaluatorResult) or result.answer is None or result.exception:
            return result

        query, evaluable = eval_sample
        if not isinstance(evaluable, AgentAnswer) or not evaluable.text:
            return result

        answer_format = result.answer
        if not isinstance(answer_format, RubricPointwiseAnswerFormat):
            return result

        weighted_sum = answer_format.average_score * sum(
            (c.criterion.weight if c.criterion.weight is not None else 1.0) for c in answer_format.criteria
        )
        total_weight = sum(
            (c.criterion.weight if c.criterion.weight is not None else 1.0) for c in answer_format.criteria
        )

        evidence_recall_result = None
        citation_quality_result = None

        if self.config.evidence_recall:
            snippets = get_evidence_snippets(query, self.config.evidence_snippets, self.criteria_cache)
            evidence_recall_result = await evaluate_evidence_recall(self.llm_provider, evaluable.text, snippets)
            weighted_sum += evidence_recall_result.recall * self.config.evidence_recall_weight
            total_weight += self.config.evidence_recall_weight

        if self.config.citation_quality:
            relevant_doc_ids = list(query.retrieved_docs.keys())
            citation_quality_result = await evaluate_citation_quality(
                self.llm_provider, evaluable.text, relevant_doc_ids
            )
            avg_citation_score = (
                citation_quality_result.claims_with_citations_ratio
                + citation_quality_result.citations_with_excerpts_ratio
            ) / 2.0
            weighted_sum += avg_citation_score * self.config.citation_quality_weight
            total_weight += self.config.citation_quality_weight

        updated_answer = answer_format.model_copy(
            update={
                "average_score": weighted_sum / total_weight if total_weight > 0 else 0.0,
                "evidence_recall": evidence_recall_result,
                "citation_quality": citation_quality_result,
            }
        )
        return result.model_copy(update={"answer": updated_answer})
