from __future__ import annotations

import logging
from collections.abc import Iterator
from typing import Any

from pydantic import BaseModel, field_validator
from typing_extensions import Self

from ragelo.types.evaluables import AgentAnswer, Document, Evaluable, PairwiseGame
from ragelo.types.results import EvaluatorResult, RetrievalEvaluatorResult

logger = logging.getLogger(__name__)


class Query(BaseModel):
    """A user query that can have retrieved documents and agent answers.
    Args:
        qid str: The query ID.
        query str: The query text.
        metadata Optional[dict[str, Any]]: Metadata that can be templated in the prompt.
        retrieved_docs dict[str, Document]: A dictionary of retrieved documents, where the key is the document ID.
        answers list[AgentAnswer]: The list of agent answers.
        pairwise_games list[PairwiseGame]: The list games to be played between agent's answers.
            Generated by the evaluator.
    """

    qid: str
    query: str
    metadata: dict[str, Any] | None = None
    retrieved_docs: dict[str, Document] = {}
    answers: dict[str, AgentAnswer] = {}
    pairwise_games: dict[str, PairwiseGame] = {}

    @field_validator("qid", mode="before")
    def qid_into_string(cls, v):
        if not isinstance(v, str):
            try:
                v = str(v)
            except ValueError:
                raise ValueError("qid must be a string or convertible to a string")
        return v

    def add_metadata(self, metadata: dict[str, Any] | None):
        """Adds metadata to the query that may be templated in the prompt.
        Args:
            metadata dict[str, Any]: The metadata to add to the query.
        """
        if not metadata:
            return
        if self.metadata is None:
            self.metadata = {}
        for k in metadata:
            if k in self.metadata:
                logger.warning(
                    f"Metadata {k} for query {self.qid} is being overwritten!\n"
                    f"Old metadata: {self.metadata[k]}\n"
                    f"New metadata: {metadata[k]}\n"
                )
            self.metadata[k] = metadata[k]

    def add_retrieved_docs(
        self,
        docs: list,
        agent: str | None = None,
        force: bool = False,
    ):
        """
        Add a list of retrieved documents to the query.
        Args:
            docs (list[Document | str] | list[Tuple[Document | str], float]): The list of documents
                (either the objects or the texts) to add to the query.
                Optionally, a score can be provided for each document.
            agent (str): The agent that retrieved the documents.
            force (bool): Whether to overwrite existing documents.
        """
        # First, transform all of the strings into Document objects.
        # If an agent name was provided, but no score information exists,
        # assume the list is ranked and assign a score of 1/(n+1) to each document.
        for idx, doc in enumerate(docs):
            if isinstance(doc, tuple):
                doc, score = doc
                if agent is None:
                    raise ValueError(
                        "If you provide a score for each retrieved document, you should also provide an agent name."
                    )
            elif agent is not None:
                score = 1 / (idx + 1)
            else:
                score = None
            self.add_retrieved_doc(doc, score=score, agent=agent, force=force)

    def add_retrieved_doc(
        self,
        doc: Document,
        score: float | None = None,
        agent: str | None = None,
        force: bool = False,
        exist_ok: bool = False,
    ):
        """Add a retrieved document to the query.
        Args:
            doc Document: The document object retrieved for the query.
            score float: The score of the document when retrieved.
            agent str: The agent that retrieved the document.
        """
        retrieved_by = doc.retrieved_by
        doc = self.retrieved_docs.get(doc.did, doc.model_copy(deep=True))
        doc.retrieved_by.update(retrieved_by)
        if agent is not None:
            doc.add_retrieved_by(agent, score, force, exist_ok)
        if doc.did in self.retrieved_docs and not force:
            if not exist_ok:
                logger.info(f"Query {self.qid} already have a document {doc.did} retrieved.")
            return

        self.retrieved_docs[doc.did] = doc

    def add_agent_answer(self, answer: AgentAnswer, force: bool = False, exist_ok: bool = False) -> bool:
        """Add an answer generated by an agent to the query.
        Args:
            answer AgentAnswer: The answer object to add to the query.
            force bool: Whether to overwrite existing answers.
            exist_ok bool: Whether to raise an error if the answer already exists.
        """
        agent = answer.agent
        if answer.agent in self.answers and not force:
            if not exist_ok:
                logger.info(f"Answer from agent {answer.agent} already exists in query {self.qid}")
            return False
        self.answers[agent] = answer
        return True

    def get_pairwise_game(self, agent_a: str, agent_b: str) -> PairwiseGame | None:
        sorted_agents = sorted([agent_a, agent_b])
        game_key = f"{sorted_agents[0]}-{sorted_agents[1]}"
        return self.pairwise_games.get(game_key, None)

    def add_pairwise_game(self, agent_a: str, agent_b: str) -> PairwiseGame:
        game = PairwiseGame(
            qid=self.qid,
            agent_a_answer=self.answers[agent_a],
            agent_b_answer=self.answers[agent_b],
        )
        self.pairwise_games[game.game_id] = game
        return game

    def add_evaluation(
        self,
        evaluable: Evaluable,
        evaluation: EvaluatorResult,
        force: bool = False,
        exist_ok: bool = False,
    ) -> bool:
        """Add an evaluation to the query.
        Args:
            evaluable Evaluable: The evaluable object to add the evaluation to.
            evaluation EvaluatorResult | EloTournamentResult: The evaluation result to add to the query.
            force bool: Whether to overwrite existing evaluations.
            exist_ok bool: Whether to raise an error if the evaluation already exists.
        """
        # Import here to avoid circular imports
        from ragelo.evaluators.evaluator_utils import resolve_evaluator_result_type

        expected_result_type = resolve_evaluator_result_type(evaluation.evaluator_name, evaluable)
        if not isinstance(evaluation, expected_result_type):
            evaluator_name = evaluation.evaluator_name
            raise TypeError(
                f"Evaluator {evaluator_name} must produce a {expected_result_type} for "
                f"{evaluable.__class__.__name__}; got {type(evaluation)}"
            )

        # Enforce single, consistent type per evaluator name on this evaluable
        evaluator_name = evaluation.evaluator_name
        if evaluator_name in evaluable.evaluations and not force:
            if not exist_ok:
                evaluable_id = getattr(evaluable, "did", getattr(evaluable, "agent", type(evaluable).__name__))
                logger.warning(
                    f"Evaluable {evaluable_id} in query {self.qid} already has an evaluation for {evaluator_name}."
                )
            return False
        evaluable.evaluations[evaluator_name] = evaluation
        return True

    def get_qrels(
        self,
        relevance_threshold: int = 0,
        retrieval_evaluator_name: str | None = None,
    ) -> dict[str, float]:
        """Get a qrels-formatted dictionary with the relevance of the retrieved documents.
        Args:
            relevance_threshold int: The minimum relevance value to consider a document as relevant.
                Documents with a relevance lower than this value will be considered as 0.
            retrieval_evaluator_name str: The name of the retrieval evaluator to use to get the relevance
                of the documents.
        """
        qrels = {}
        if len(self.retrieved_docs) == 0:
            logger.warning(f"Query {self.qid} does not have any retrieved documents. Returning empty qrels.")
        docs_without_relevance = 0
        for did, document in self.retrieved_docs.items():
            if retrieval_evaluator_name is None:
                for key, value in document.evaluations.items():
                    if isinstance(value, RetrievalEvaluatorResult):
                        retrieval_evaluator_name = key
                        break
                if retrieval_evaluator_name is None:
                    logger.warning("No valid retrieval evaluator result found.")
                    docs_without_relevance += 1
                    continue
                logger.info(f"No retrieval evaluator name provided. Using {retrieval_evaluator_name}.")
            if retrieval_evaluator_name not in document.evaluations:
                logger.warning(
                    f"Document {did} in query {self.qid} does not have an evaluation from {retrieval_evaluator_name}."
                )
                docs_without_relevance += 1
                continue
            evaluation = document.evaluations[retrieval_evaluator_name]
            # Read flattened score
            try:
                score = getattr(evaluation, "score")
            except AttributeError:
                logger.warning(f"Evaluation {evaluation} does not have a score attribute.")
                docs_without_relevance += 1
                continue
            if not isinstance(score, int) and not isinstance(score, float):
                logger.warning(f"Score {score} is not an integer or a float.")
                docs_without_relevance += 1
                continue

            qrels[did] = 0.0 if score < relevance_threshold else score
        if docs_without_relevance > 0:
            logger.warning(f"Query {self.qid} has {docs_without_relevance} documents without relevance.")
        if docs_without_relevance == len(self.retrieved_docs):
            logger.error(f"Query {self.qid} has no documents without relevance.")
        return qrels

    def get_runs(self, agents: list[str] | None = None) -> dict[str, dict[str, dict[str, float]]]:
        """Get a trec-style run dictionary with the documents retrieved by the agents provided.
        If no agents are provided, all agents will be included.
        Args:
            agents list[str]: The list of agent IDs to include in the run.
        """
        runs: dict[str, dict[str, dict[str, float]]] = {}
        for did, document in self.retrieved_docs.items():
            for agent, score in document.retrieved_by.items():
                if agents is not None and agent not in agents:
                    continue
                if agent not in runs:
                    runs[agent] = {self.qid: {}}
                runs[agent][self.qid][did] = float(score)

        if len(runs) == 0:
            logger.warning(f"Query {self.qid} does not have any retrieved documents with an agent assigned.")
        return runs

    def retrieved_docs_iter(self) -> Iterator[Document]:
        return iter(self.retrieved_docs.values())

    @classmethod
    def assemble_query(cls, query: Self | str, metadata: dict[str, Any] | None = None) -> Self:
        """Assembles a Query object from a Query object or a query text.
        Args:
            query Query | str: The query object or the query text.
            metadata dict[str, Any]: Metadata to add to the query.
        """
        if isinstance(query, Query):
            # If it's already the right type and has no additional metadata, return as-is
            if type(query) is cls and not metadata:
                return query
            # Otherwise, create a new instance of the correct class with the data
            query_data = query.model_dump()
            if metadata:
                if query_data.get("metadata"):
                    query_data["metadata"].update(metadata)
                else:
                    query_data["metadata"] = metadata
            return cls(**query_data)
        return cls(qid="<no_qid>", query=query, metadata=metadata)
